name: CI

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch
  pull_request:
    branches:
      - master  # or 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Add this if you're using themes as submodules
          fetch-depth: 0    # Add this for full git history

      - name: Read node-version from .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Add this if you're using SCSS/SASS

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'  # or 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public