name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read node-version from .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Add these debugging steps
      - name: Debug - Show Hugo version
        run: hugo version

      - name: Debug - List directory structure before build
        run: ls -la

      - name: Build
        run: hugo --minify

      # Add more debugging steps
      - name: Debug - List public directory after build
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of public directory:"
          ls -la public || echo "public directory not found"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}