name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Important for theme files

      - name: Read node-version from .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      # Modified npm install steps
      - name: Install dependencies
        run: |
          npm install
          npm install -D @fullhuman/postcss-purgecss@6.0.0
          npm install -D @tailwindcss/typography@0.4.1
          npm install -D autoprefixer@10.4.20
          npm install -D postcss@8.4.47
          npm install -D postcss-cli@11.0.0
          npm install -D postcss-import@16.1.0
          npm install -D tailwindcss@2.2.16

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Add debugging for CSS processing
      - name: Debug CSS setup
        run: |
          echo "Contents of assets/css:"
          ls -la assets/css || echo "No assets/css directory"
          echo "Checking PostCSS config:"
          cat postcss.config.js || echo "No postcss.config.js found"
          echo "Checking Tailwind config:"
          cat tailwind.config.js || echo "No tailwind.config.js found"

      # Add obfuscation step before build
      - name: Obfuscate JavaScript
        run: npm run obfuscate

      # Add debugging for build process
      - name: Debug Build Process
        run: |
          echo "Contents of assets/js:"
          ls -la assets/js || echo "No assets/js directory"
          echo "Contents of assets/js/src:"
          ls -la assets/js/src || echo "No assets/js/src directory"

      - name: Build
        run: hugo --minify

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}